apiVersion: apps/v1
kind: Deployment
metadata:
  name: "frontend-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend-app"
  template:
    metadata:
      labels:
        app: "frontend-app"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend-container
        image: ghcr.io/superellips/frontend:88a0ea616417ed823238cd03a5f0f25d0314608d
        # resources:
        #   limits:
        #     cpu: "10"
        #     memory: "100Mi"
        #   requests:
        #     cpu: "10 "
        #     memory: "50Mi"
        ports:
        - containerPort: 8080
        envFrom: 
        - configMapRef:
            name: frontend-config