apiVersion: apps/v1
kind: Deployment
metadata:
  name: "frontend-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend-app"
  template:
    metadata:
      labels:
        app: "frontend-app"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend-container
        image: ghcr.io/superellips/frontend:051f8aff4fc8d889aa948cb56252a0ce3cbe703d
        # resources:
        #   limits:
        #     cpu: "10"
        #     memory: "100Mi"
        #   requests:
        #     cpu: "10 "
        #     memory: "50Mi"
        ports:
        - containerPort: 8080